version: "3"
volumes:
  postgres-data:
services:
  main:
    image: application
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - default
    volumes:
      - ./logs:/app/logs
    depends_on:
      - application-db
    environment:
      WAIT_HOSTS: application-db:application-db
  application-db:
    image: postgres:latest
    expose:
      - "5432"
    volumes:
      - ./scripts/create.sql:/docker-entrypoint-initdb.d/init.sql
      - ./scripts/constraints.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql
    env_file:
      - ./env/db.env
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G

